name: genIA

services:
  frontend:
    container_name: frontend
    image: blackvsk/genia:front
    ports:
      - 80:80

  MS:
    container_name: MS
    image: blackvsk/genia:MS
    env_file:
      - ms.env
    ports:
      - 3001:3000

  backend: 
    container_name: backend
    image: blackvsk/genia:back
    env_file:
      - back.env
    ports:
      - 3000:3002

  